apiVersion: v1
kind: ConfigMap
metadata:
  name: mapfile
data:
  condormapfile: |
    SCITOKENS https://iam-escape.cloud.cnaf.infn.it/ escape@users.htcondor.org
    PASSWORD (*.) condor
    GSI (.*) anonymous
