kind: Service
apiVersion: v1
metadata:
  name: schedd
spec:
 selector:
    app.kubernetes.io/name: schedd
 #clusterIP: None
 type: NodePort
 ports:
  - protocol: TCP
    name: schedd
    targetPort: 31618
    port: 31618
    nodePort: 31618
---
kind: Service
apiVersion: v1
metadata:
  name: master
spec:
  selector:
    app.kubernetes.io/name: master
  #clusterIP: None
  type: NodePort
  ports:
  - protocol: TCP
    name: collector
    port: 30618
    targetPort: 30618
    nodePort: 30618
